Fix missing include in rasterizer_impl.h
This is to fix: gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.h(24): error: namespace "std" has no member "uintptr_t"